browser=chrome
salesforce.url=https://login.salesforce.com/?locale=in
valid.username=testuser@salesforce.com
valid.password=ValidPassword123!
invalid.username=invalid@salesforce.com
invalid.password=WrongPassword123!
implicit.wait=10
explicit.wait=15
